# Generated by Django 5.0.2 on 2024-03-04 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('mail', models.EmailField(blank=True, max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
